version: '3.9'

services:
  app:
    build:
      context: .
    container_name: rag-bot-app
    ports:
      - "8000:8000"    # FastAPI
      - "8502:8501"    # Streamlit
    env_file:
      - .env
    volumes:
      - .:/app